spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:file:./data/emwalimu;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            '[non_contextual_creation]': true
        id:
          '[new_generator_mappings]': true
springdoc:
  pathsToMatch: /api/**
  
server:
  port: 8080
  address: 0.0.0.0
